language: rust

stages:
- test
# Deploy stage on runs on a valid semver tag, regardless of branch
- name: deploy
  if: tag =~ /^\d+\.\d+\.\d+.*$/

env:
  global:
  # We always want full stack traces in the event of a panic
  - RUST_BACKTRACE=1

# See http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
# this just allows us to give _somewhat_ better views of the build steps
before_script:
- export -f travis_nanoseconds
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish

matrix:
  fast_finish: true

  include:
  #  _      _       _   
  # | |    (_)     | |  
  # | |     _ _ __ | |_ 
  # | |    | | '_ \| __|
  # | |____| | | | | |_ 
  # |______|_|_| |_|\__|

  # 1. Ensure rustfmt does not produce diffs. We always use
  # the default rustfmt settings.
  # 2. Ensure there are no clippy warnings.
  - name: "stable lint"
    # We could use a lint stage here, but prefer to go wide
    #
    stage: test
    rust: stable
    os: linux
    script: .ci/lint.sh

  # We do the exact same checks on the beta channel, as both
  # rustfmt and clippy can change their behavior between releases
  # and introduce new diffs/lints compared to stable
  - name: "beta lint"
    stage: test
    rust: beta
    os: linux
    script: .ci/lint.sh
    if: branch = master AND tag IS blank

  #  _______        _   
  # |__   __|      | |  
  #    | | ___  ___| |_ 
  #    | |/ _ \/ __| __|
  #    | |  __/\__ \ |_ 
  #    |_|\___||___/\__|

  # Tests all platforms on stable
  # and additionally running beta and nightly
  # tests on Linux as Linux runs are generally
  # faster in every aspect on Travis

  - name: "stable test linux"
    stage: test
    rust: stable
    os: linux
    script: .ci/test.sh

  - name: "beta test linux"
    stage: test
    rust: beta
    os: linux
    script: .ci/test.sh
    if: branch = master AND tag IS blank

  - name: "stable test osx"
    rust: stable
    os: osx
    script: .ci/test.sh

  - name: "stable test windows"
    rust: stable
    os: windows
    script: .ci/test.sh

  # Add more testing stages if you have them!

  #  _____       _     _ _     _     
  # |  __ \     | |   | (_)   | |    
  # | |__) |   _| |__ | |_ ___| |__  
  # |  ___/ | | | '_ \| | / __| '_ \ 
  # | |   | |_| | |_) | | \__ \ | | |
  # |_|    \__,_|_.__/|_|_|___/_| |_|

  # Publish a release to crates.io. The only
  # thing you need to do is to is change the repo
  # below, and provide the output of the `travis encrypt <crates_io_token>`
  # in the deploy.token.secure value. Note that you will
  # need to encrypt the same key for different repos, you
  # can't just copy the value from another repo.
  - stage: deploy
    rust: stable
    os: linux
    script: echo "deploying $TRAVIS_TAG to crates.io"
    env:
      global:
      - secure: Jz67Cb8eT3mzE+hnh1RS/wkjLJeX8wvUGTD1tTDvsm9jepgZSaG4X0vwrN8meIMiSCXeZ91s2U15jJWVHb17sJYLioyZrLcmS868KYkTbOpXkFYeJLpDB7D0+wW8u8512Z45suHmCw8IfLF6SZHh0To40dySub+OU88tw+7Pp/JlaL8wnxh2WrpT+6a66I0P+71M97KEqu9TI6/5U7R+lvG/a6+HUjQNIVogtfzyEb/OSo1vvBry8WDqPqlqXyJb6mqaq6QJZ8eigDz3BmESZO5hQ8y7AMZD/523Lr0MLj0X9yh2M0aWEVvZBYwEMAUbfnvBKzOH3pQdxFkTCbEG5ZARr1yU08d5zCguceI+SvDtIGvCY+I+wthl+5eIBZ81NKOonXNJj+ZQHBHjVW3E6WgteEq6mG74VGLIjRwQ0r9ayZIMpO5j0gIol+ehqcTBOljH9pjGoa0nbtYyif3vnQwOcErgcuUQ94K3VP+2VgzMJHaSbSYsPI6kJ2YhpHBsMcwltblW5CkSxBCFQ5TwZ4aZzD+0kngpWO+sl+C7vHhzULSutKwYr9qjTVnEChEn3EMm/U1os6GOQU8L4NUowkiG6qr2/a0U5XO5igY79/WqikWLxJUrzKPyuH86IZTaczb5q8Uf+EWVv5UbpG6dcNn4iGbbbS6wcnoCdbXjyB0=
    deploy:
      provider: script
      script: bash .ci/crates_io_deploy.sh $CRATES_TOKEN
      on:
        repo: EmbarkStudios/texture-synthesis
        tags: true

  # Keep these step if you want to publish tarballed releases to Github.
  # Generally, this will only make sense for binary crates, so normally
  # you will want to remove them. If you do, you can also remove the
  # .ci/prep_deploy and .ci/checksum.ps1

  - name: "publish x86_64-unknown-linux-musl"
    stage: deploy
    rust: stable
    os: linux
    env:
    - DEPLOY=1
    - TARGET=x86_64-unknown-linux-musl
    script:
    - .ci/install_musl.sh
    - .ci/prep_deploy.sh

  - name: "publish x86_64-pc-windows-msvc"
    stage: deploy
    os: windows
    env:
    - DEPLOY=1
    - TARGET=x86_64-pc-windows-msvc
    # Override Travis' rust version, we don't want the gnu default
    # caused Travis running in bash, the normal Travis Rust install
    # process will pick up this environment variable
    - TRAVIS_RUST_VERSION=stable-x86_64-pc-windows-msvc
    script:
    - .ci/prep_deploy.sh

  - name: "publish x86_64-apple-darwin"
    stage: deploy
    rust: stable
    os: osx
    env:
    - DEPLOY=1
    - TARGET=x86_64-apple-darwin
    script:
    - .ci/prep_deploy.sh

# Just as with the crates.io publish step, you will need
# to encrypt your API key with `travis encrypt <github_token>` and
# place it in the deploy.api_key.secure value
deploy:
- provider: releases
  api_key:
    secure: Bl70Wlwi1dueZY159tMygxbPri7t5LHDUnuTzOvuf/gUFHls0e2LvVeWI0QTF+MEEP+bzdbzkGxnNWfzL4jQYOhDEqInPFEfebwMFQ3tLn0rFm2Pz0oaAcSg4viYY7vBnFcVoxh9VvN/Elc51xD0ovCpqfIwX2U4KwgQyCZ0zJRZ1PAbzZR9lm4tGmqu4Wv/dUNxwCIO/BLxPRPdc3idowf7HTESIGdaq/2v7Lqp0WUT4Thn8ueN7GdDRGIMGs4TXIlvi1cZ9Hp1nLjpvUMiNw4ydwCkOeIMMA8HnwO0zCkvxgqL79IBSHFOQf+uMYH8orW4En+BHA3iBzlJJCUzJ1Djrlkl8Bb+0NvwwPVrG0rhtfhjuoHA00xp9AgNfCGVua4NDPt5ECrTWKE34qD+qCS6owd3CxLvgL+anT7g54GndEmTfBuPfCEOsQ2Darf4jI8eJFtQh0bFjuKbVwiuGOT16d9I//q4Jlf6wliq0qRLkkxnyQRDY0g+gYRWWa5DES1/t7JFu9iNc2EbGDuzKp33x8T8+ovgdvO+dS+JzRFjp3PbPa7Ntl8WsuzNAyk14TcOzKIvKQAe5xLotDLrou/2mt8LvuA6LsiXHsfjdMCKuwKFlZ254/h/uTmp+uiNCTyAK+eICXObePhqEH5zO3BZoz43M9UrftynixyLkL4=
  file:
  - texture-synthesis-$TRAVIS_TAG-$TARGET.tar.gz
  - texture-synthesis-$TRAVIS_TAG-$TARGET.tar.gz.sha256
  skip_cleanup: true
  on:
    condition: $DEPLOY = 1
    repo: EmbarkStudios/texture-synthesis
    tags: true
