[package]
name = "texture-synthesis-cli"
description = "A CLI for texture-synthesis"
repository = "https://github.com/EmbarkStudios/texture-synthesis"
version = "0.3.0"
authors = [
    "Embark <opensource@embark-studios.com>",
    "Anastasia Opara <anastasiaopara@gmail.com>",
    "Tomasz Stachowiak <h3@h3.gd>",
]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/texture-synthesis"
homepage = "https://github.com/EmbarkStudios/texture-synthesis"
categories = ["multimedia::images"]
keywords = ["texture", "synthesis", "procedural", "cli"]

[[bin]]
name = "texture-synthesis"
path = "src/main.rs"

[dependencies]
atty = "0.2.13" # indicatif's tty detection only works with stdout for some reason
indicatif = "0.11.0"
minifb = { version = "0.13.0", optional = true }
rand = "0.6.4"
structopt = "0.3.0"
texture-synthesis = { version = "0.3.0", path = "../lib" }

[features]
default = []
progress = ["minifb"]
