[package]
name = "texture-synthesis-cli"
description = "A CLI for texture-synthesis"
repository = "https://github.com/EmbarkStudios/texture-synthesis"
version = "0.2.0"
authors = [
    "Embark <opensource@embark-studios.com>",
    "anastasia opara <anastasiaopara@gmail.com>",
    "tomasz stachowiak <h3@h3.gd>",
]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "../README.md"
documentation = "https://docs.rs/texture-synthesis"
homepage = "https://github.com/EmbarkStudios/texture-synthesis"
categories = ["multimedia::images"]
keywords = ["texture", "synthesis", "procedural", "cli"]

[[bin]]
name = "texture-synthesis"
path = "src/main.rs"

[dependencies]
indicatif = "0.11.0"
piston_window = "0.85.0"
rand = "0.6.4"
structopt = "0.3.0"
texture-synthesis = { version = "0.2.0", path = "../lib" }
